//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Torshify.Origo.Shell.PlaylistPlayerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlaylistTrack", Namespace="http://schemas.torshify/v1")]
    [System.SerializableAttribute()]
    public partial class PlaylistTrack : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsQueuedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Torshify.Origo.Shell.PlaylistPlayerService.Track TrackField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsQueued {
            get {
                return this.IsQueuedField;
            }
            set {
                if ((this.IsQueuedField.Equals(value) != true)) {
                    this.IsQueuedField = value;
                    this.RaisePropertyChanged("IsQueued");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Torshify.Origo.Shell.PlaylistPlayerService.Track Track {
            get {
                return this.TrackField;
            }
            set {
                if ((object.ReferenceEquals(this.TrackField, value) != true)) {
                    this.TrackField = value;
                    this.RaisePropertyChanged("Track");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Track", Namespace="http://schemas.torshify/v1")]
    [System.SerializableAttribute()]
    public partial class Track : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Torshify.Origo.Shell.PlaylistPlayerService.Album AlbumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DiscField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PopularityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsStarredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OfflineStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsLocalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Torshify.Origo.Shell.PlaylistPlayerService.Artist[] ArtistsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public Torshify.Origo.Shell.PlaylistPlayerService.Album Album {
            get {
                return this.AlbumField;
            }
            set {
                if ((object.ReferenceEquals(this.AlbumField, value) != true)) {
                    this.AlbumField = value;
                    this.RaisePropertyChanged("Album");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Index {
            get {
                return this.IndexField;
            }
            set {
                if ((this.IndexField.Equals(value) != true)) {
                    this.IndexField = value;
                    this.RaisePropertyChanged("Index");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Disc {
            get {
                return this.DiscField;
            }
            set {
                if ((this.DiscField.Equals(value) != true)) {
                    this.DiscField = value;
                    this.RaisePropertyChanged("Disc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int Popularity {
            get {
                return this.PopularityField;
            }
            set {
                if ((this.PopularityField.Equals(value) != true)) {
                    this.PopularityField = value;
                    this.RaisePropertyChanged("Popularity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool IsStarred {
            get {
                return this.IsStarredField;
            }
            set {
                if ((this.IsStarredField.Equals(value) != true)) {
                    this.IsStarredField = value;
                    this.RaisePropertyChanged("IsStarred");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string OfflineStatus {
            get {
                return this.OfflineStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.OfflineStatusField, value) != true)) {
                    this.OfflineStatusField = value;
                    this.RaisePropertyChanged("OfflineStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public bool IsLocal {
            get {
                return this.IsLocalField;
            }
            set {
                if ((this.IsLocalField.Equals(value) != true)) {
                    this.IsLocalField = value;
                    this.RaisePropertyChanged("IsLocal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public Torshify.Origo.Shell.PlaylistPlayerService.Artist[] Artists {
            get {
                return this.ArtistsField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistsField, value) != true)) {
                    this.ArtistsField = value;
                    this.RaisePropertyChanged("Artists");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Album", Namespace="http://schemas.torshify/v1")]
    [System.SerializableAttribute()]
    public partial class Album : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoverIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAvailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Torshify.Origo.Shell.PlaylistPlayerService.Artist ArtistField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string CoverID {
            get {
                return this.CoverIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CoverIDField, value) != true)) {
                    this.CoverIDField = value;
                    this.RaisePropertyChanged("CoverID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool IsAvailable {
            get {
                return this.IsAvailableField;
            }
            set {
                if ((this.IsAvailableField.Equals(value) != true)) {
                    this.IsAvailableField = value;
                    this.RaisePropertyChanged("IsAvailable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public Torshify.Origo.Shell.PlaylistPlayerService.Artist Artist {
            get {
                return this.ArtistField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistField, value) != true)) {
                    this.ArtistField = value;
                    this.RaisePropertyChanged("Artist");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Artist", Namespace="http://schemas.torshify/v1")]
    [System.SerializableAttribute()]
    public partial class Artist : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PortraitIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PortraitID {
            get {
                return this.PortraitIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PortraitIDField, value) != true)) {
                    this.PortraitIDField = value;
                    this.RaisePropertyChanged("PortraitID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.torshify/v1", ConfigurationName="PlaylistPlayerService.PlaylistPlayerService")]
    public interface PlaylistPlayerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.torshify/v1/PlaylistPlayerService/Initialize", ReplyAction="http://schemas.torshify/v1/PlaylistPlayerService/InitializeResponse")]
        void Initialize(string[] links);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.torshify/v1/PlaylistPlayerService/Enqueue", ReplyAction="http://schemas.torshify/v1/PlaylistPlayerService/EnqueueResponse")]
        void Enqueue(string[] links);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.torshify/v1/PlaylistPlayerService/Next", ReplyAction="http://schemas.torshify/v1/PlaylistPlayerService/NextResponse")]
        void Next();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.torshify/v1/PlaylistPlayerService/Previous", ReplyAction="http://schemas.torshify/v1/PlaylistPlayerService/PreviousResponse")]
        void Previous();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.torshify/v1/PlaylistPlayerService/GetCurrent", ReplyAction="http://schemas.torshify/v1/PlaylistPlayerService/GetCurrentResponse")]
        Torshify.Origo.Shell.PlaylistPlayerService.PlaylistTrack GetCurrent();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.torshify/v1/PlaylistPlayerService/GetPlaylist", ReplyAction="http://schemas.torshify/v1/PlaylistPlayerService/GetPlaylistResponse")]
        Torshify.Origo.Shell.PlaylistPlayerService.PlaylistTrack[] GetPlaylist();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.torshify/v1/PlaylistPlayerService/SetShuffle", ReplyAction="http://schemas.torshify/v1/PlaylistPlayerService/SetShuffleResponse")]
        void SetShuffle(bool shuffle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.torshify/v1/PlaylistPlayerService/SetRepeat", ReplyAction="http://schemas.torshify/v1/PlaylistPlayerService/SetRepeatResponse")]
        void SetRepeat(bool repeat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.torshify/v1/PlaylistPlayerService/GetRepeat", ReplyAction="http://schemas.torshify/v1/PlaylistPlayerService/GetRepeatResponse")]
        bool GetRepeat();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.torshify/v1/PlaylistPlayerService/GetShuffle", ReplyAction="http://schemas.torshify/v1/PlaylistPlayerService/GetShuffleResponse")]
        bool GetShuffle();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PlaylistPlayerServiceChannel : Torshify.Origo.Shell.PlaylistPlayerService.PlaylistPlayerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlaylistPlayerServiceClient : System.ServiceModel.ClientBase<Torshify.Origo.Shell.PlaylistPlayerService.PlaylistPlayerService>, Torshify.Origo.Shell.PlaylistPlayerService.PlaylistPlayerService {
        
        public PlaylistPlayerServiceClient() {
        }
        
        public PlaylistPlayerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlaylistPlayerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlaylistPlayerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlaylistPlayerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Initialize(string[] links) {
            base.Channel.Initialize(links);
        }
        
        public void Enqueue(string[] links) {
            base.Channel.Enqueue(links);
        }
        
        public void Next() {
            base.Channel.Next();
        }
        
        public void Previous() {
            base.Channel.Previous();
        }
        
        public Torshify.Origo.Shell.PlaylistPlayerService.PlaylistTrack GetCurrent() {
            return base.Channel.GetCurrent();
        }
        
        public Torshify.Origo.Shell.PlaylistPlayerService.PlaylistTrack[] GetPlaylist() {
            return base.Channel.GetPlaylist();
        }
        
        public void SetShuffle(bool shuffle) {
            base.Channel.SetShuffle(shuffle);
        }
        
        public void SetRepeat(bool repeat) {
            base.Channel.SetRepeat(repeat);
        }
        
        public bool GetRepeat() {
            return base.Channel.GetRepeat();
        }
        
        public bool GetShuffle() {
            return base.Channel.GetShuffle();
        }
    }
}
