//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Torshify.Origo.Shell.LoginService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.torshify/v1", ConfigurationName="LoginService.LoginService")]
    public interface LoginService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.torshify/v1/LoginService/IsLoggedIn", ReplyAction="http://schemas.torshify/v1/LoginService/IsLoggedInResponse")]
        bool IsLoggedIn();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.torshify/v1/LoginService/GetRememberedUser", ReplyAction="http://schemas.torshify/v1/LoginService/GetRememberedUserResponse")]
        string GetRememberedUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.torshify/v1/LoginService/Login", ReplyAction="http://schemas.torshify/v1/LoginService/LoginResponse")]
        void Login(string userName, string password, bool remember);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.torshify/v1/LoginService/ForgetRememberedUser", ReplyAction="http://schemas.torshify/v1/LoginService/ForgetRememberedUserResponse")]
        void ForgetRememberedUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.torshify/v1/LoginService/Relogin", ReplyAction="http://schemas.torshify/v1/LoginService/ReloginResponse")]
        void Relogin();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoginServiceChannel : Torshify.Origo.Shell.LoginService.LoginService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginServiceClient : System.ServiceModel.ClientBase<Torshify.Origo.Shell.LoginService.LoginService>, Torshify.Origo.Shell.LoginService.LoginService {
        
        public LoginServiceClient() {
        }
        
        public LoginServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IsLoggedIn() {
            return base.Channel.IsLoggedIn();
        }
        
        public string GetRememberedUser() {
            return base.Channel.GetRememberedUser();
        }
        
        public void Login(string userName, string password, bool remember) {
            base.Channel.Login(userName, password, remember);
        }
        
        public void ForgetRememberedUser() {
            base.Channel.ForgetRememberedUser();
        }
        
        public void Relogin() {
            base.Channel.Relogin();
        }
    }
}
