//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Torshify.Origo.Shell.QueryService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryResult", Namespace="http://schemas.torshify/v1")]
    [System.SerializableAttribute()]
    public partial class QueryResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Torshify.Origo.Shell.QueryService.Album[] AlbumsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Torshify.Origo.Shell.QueryService.Artist[] ArtistsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Torshify.Origo.Shell.QueryService.Track[] TracksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalAlbumsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalArtistsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalTracksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QueryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DidYouMeanField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Torshify.Origo.Shell.QueryService.Album[] Albums {
            get {
                return this.AlbumsField;
            }
            set {
                if ((object.ReferenceEquals(this.AlbumsField, value) != true)) {
                    this.AlbumsField = value;
                    this.RaisePropertyChanged("Albums");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Torshify.Origo.Shell.QueryService.Artist[] Artists {
            get {
                return this.ArtistsField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistsField, value) != true)) {
                    this.ArtistsField = value;
                    this.RaisePropertyChanged("Artists");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Torshify.Origo.Shell.QueryService.Track[] Tracks {
            get {
                return this.TracksField;
            }
            set {
                if ((object.ReferenceEquals(this.TracksField, value) != true)) {
                    this.TracksField = value;
                    this.RaisePropertyChanged("Tracks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int TotalAlbums {
            get {
                return this.TotalAlbumsField;
            }
            set {
                if ((this.TotalAlbumsField.Equals(value) != true)) {
                    this.TotalAlbumsField = value;
                    this.RaisePropertyChanged("TotalAlbums");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int TotalArtists {
            get {
                return this.TotalArtistsField;
            }
            set {
                if ((this.TotalArtistsField.Equals(value) != true)) {
                    this.TotalArtistsField = value;
                    this.RaisePropertyChanged("TotalArtists");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int TotalTracks {
            get {
                return this.TotalTracksField;
            }
            set {
                if ((this.TotalTracksField.Equals(value) != true)) {
                    this.TotalTracksField = value;
                    this.RaisePropertyChanged("TotalTracks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Query {
            get {
                return this.QueryField;
            }
            set {
                if ((object.ReferenceEquals(this.QueryField, value) != true)) {
                    this.QueryField = value;
                    this.RaisePropertyChanged("Query");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string DidYouMean {
            get {
                return this.DidYouMeanField;
            }
            set {
                if ((object.ReferenceEquals(this.DidYouMeanField, value) != true)) {
                    this.DidYouMeanField = value;
                    this.RaisePropertyChanged("DidYouMean");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Album", Namespace="http://schemas.torshify/v1")]
    [System.SerializableAttribute()]
    public partial class Album : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoverIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAvailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Torshify.Origo.Shell.QueryService.Artist ArtistField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string CoverID {
            get {
                return this.CoverIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CoverIDField, value) != true)) {
                    this.CoverIDField = value;
                    this.RaisePropertyChanged("CoverID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool IsAvailable {
            get {
                return this.IsAvailableField;
            }
            set {
                if ((this.IsAvailableField.Equals(value) != true)) {
                    this.IsAvailableField = value;
                    this.RaisePropertyChanged("IsAvailable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public Torshify.Origo.Shell.QueryService.Artist Artist {
            get {
                return this.ArtistField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistField, value) != true)) {
                    this.ArtistField = value;
                    this.RaisePropertyChanged("Artist");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Artist", Namespace="http://schemas.torshify/v1")]
    [System.SerializableAttribute()]
    public partial class Artist : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PortraitIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PortraitID {
            get {
                return this.PortraitIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PortraitIDField, value) != true)) {
                    this.PortraitIDField = value;
                    this.RaisePropertyChanged("PortraitID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Track", Namespace="http://schemas.torshify/v1")]
    [System.SerializableAttribute()]
    public partial class Track : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Torshify.Origo.Shell.QueryService.Album AlbumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DiscField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PopularityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsStarredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OfflineStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsLocalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Torshify.Origo.Shell.QueryService.Artist[] ArtistsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public Torshify.Origo.Shell.QueryService.Album Album {
            get {
                return this.AlbumField;
            }
            set {
                if ((object.ReferenceEquals(this.AlbumField, value) != true)) {
                    this.AlbumField = value;
                    this.RaisePropertyChanged("Album");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Index {
            get {
                return this.IndexField;
            }
            set {
                if ((this.IndexField.Equals(value) != true)) {
                    this.IndexField = value;
                    this.RaisePropertyChanged("Index");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Disc {
            get {
                return this.DiscField;
            }
            set {
                if ((this.DiscField.Equals(value) != true)) {
                    this.DiscField = value;
                    this.RaisePropertyChanged("Disc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int Popularity {
            get {
                return this.PopularityField;
            }
            set {
                if ((this.PopularityField.Equals(value) != true)) {
                    this.PopularityField = value;
                    this.RaisePropertyChanged("Popularity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool IsStarred {
            get {
                return this.IsStarredField;
            }
            set {
                if ((this.IsStarredField.Equals(value) != true)) {
                    this.IsStarredField = value;
                    this.RaisePropertyChanged("IsStarred");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string OfflineStatus {
            get {
                return this.OfflineStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.OfflineStatusField, value) != true)) {
                    this.OfflineStatusField = value;
                    this.RaisePropertyChanged("OfflineStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public bool IsLocal {
            get {
                return this.IsLocalField;
            }
            set {
                if ((this.IsLocalField.Equals(value) != true)) {
                    this.IsLocalField = value;
                    this.RaisePropertyChanged("IsLocal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public Torshify.Origo.Shell.QueryService.Artist[] Artists {
            get {
                return this.ArtistsField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistsField, value) != true)) {
                    this.ArtistsField = value;
                    this.RaisePropertyChanged("Artists");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlbumBrowseResult", Namespace="http://schemas.torshify/v1")]
    [System.SerializableAttribute()]
    public partial class AlbumBrowseResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Torshify.Origo.Shell.QueryService.Album AlbumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Torshify.Origo.Shell.QueryService.Artist ArtistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] CopyrightsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReviewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Torshify.Origo.Shell.QueryService.Track[] TracksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double BackendRequestDurationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Torshify.Origo.Shell.QueryService.Album Album {
            get {
                return this.AlbumField;
            }
            set {
                if ((object.ReferenceEquals(this.AlbumField, value) != true)) {
                    this.AlbumField = value;
                    this.RaisePropertyChanged("Album");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Torshify.Origo.Shell.QueryService.Artist Artist {
            get {
                return this.ArtistField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistField, value) != true)) {
                    this.ArtistField = value;
                    this.RaisePropertyChanged("Artist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Copyrights {
            get {
                return this.CopyrightsField;
            }
            set {
                if ((object.ReferenceEquals(this.CopyrightsField, value) != true)) {
                    this.CopyrightsField = value;
                    this.RaisePropertyChanged("Copyrights");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Review {
            get {
                return this.ReviewField;
            }
            set {
                if ((object.ReferenceEquals(this.ReviewField, value) != true)) {
                    this.ReviewField = value;
                    this.RaisePropertyChanged("Review");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Torshify.Origo.Shell.QueryService.Track[] Tracks {
            get {
                return this.TracksField;
            }
            set {
                if ((object.ReferenceEquals(this.TracksField, value) != true)) {
                    this.TracksField = value;
                    this.RaisePropertyChanged("Tracks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double BackendRequestDuration {
            get {
                return this.BackendRequestDurationField;
            }
            set {
                if ((this.BackendRequestDurationField.Equals(value) != true)) {
                    this.BackendRequestDurationField = value;
                    this.RaisePropertyChanged("BackendRequestDuration");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArtistBrowsingType", Namespace="http://schemas.datacontract.org/2004/07/Torshify.Origo.Contracts.V1.Query")]
    public enum ArtistBrowsingType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Full = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoAlbums = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoTracks = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArtistBrowseResult", Namespace="http://schemas.torshify/v1")]
    [System.SerializableAttribute()]
    public partial class ArtistBrowseResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Torshify.Origo.Shell.QueryService.Artist ArtistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Torshify.Origo.Shell.QueryService.Album[] AlbumsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double BackendRequestDurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BiographyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Torshify.Origo.Shell.QueryService.Track[] TracksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] PortraitsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Torshify.Origo.Shell.QueryService.Artist[] SimilarArtistsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Torshify.Origo.Shell.QueryService.Artist Artist {
            get {
                return this.ArtistField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistField, value) != true)) {
                    this.ArtistField = value;
                    this.RaisePropertyChanged("Artist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public Torshify.Origo.Shell.QueryService.Album[] Albums {
            get {
                return this.AlbumsField;
            }
            set {
                if ((object.ReferenceEquals(this.AlbumsField, value) != true)) {
                    this.AlbumsField = value;
                    this.RaisePropertyChanged("Albums");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double BackendRequestDuration {
            get {
                return this.BackendRequestDurationField;
            }
            set {
                if ((this.BackendRequestDurationField.Equals(value) != true)) {
                    this.BackendRequestDurationField = value;
                    this.RaisePropertyChanged("BackendRequestDuration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Biography {
            get {
                return this.BiographyField;
            }
            set {
                if ((object.ReferenceEquals(this.BiographyField, value) != true)) {
                    this.BiographyField = value;
                    this.RaisePropertyChanged("Biography");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public Torshify.Origo.Shell.QueryService.Track[] Tracks {
            get {
                return this.TracksField;
            }
            set {
                if ((object.ReferenceEquals(this.TracksField, value) != true)) {
                    this.TracksField = value;
                    this.RaisePropertyChanged("Tracks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string[] Portraits {
            get {
                return this.PortraitsField;
            }
            set {
                if ((object.ReferenceEquals(this.PortraitsField, value) != true)) {
                    this.PortraitsField = value;
                    this.RaisePropertyChanged("Portraits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public Torshify.Origo.Shell.QueryService.Artist[] SimilarArtists {
            get {
                return this.SimilarArtistsField;
            }
            set {
                if ((object.ReferenceEquals(this.SimilarArtistsField, value) != true)) {
                    this.SimilarArtistsField = value;
                    this.RaisePropertyChanged("SimilarArtists");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Playlist", Namespace="http://schemas.torshify/v1")]
    [System.SerializableAttribute()]
    public partial class Playlist : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCollaborativeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OfflineStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PendingChangesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] SubscribersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Torshify.Origo.Shell.QueryService.Track[] TracksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool IsCollaborative {
            get {
                return this.IsCollaborativeField;
            }
            set {
                if ((this.IsCollaborativeField.Equals(value) != true)) {
                    this.IsCollaborativeField = value;
                    this.RaisePropertyChanged("IsCollaborative");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string OfflineStatus {
            get {
                return this.OfflineStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.OfflineStatusField, value) != true)) {
                    this.OfflineStatusField = value;
                    this.RaisePropertyChanged("OfflineStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool PendingChanges {
            get {
                return this.PendingChangesField;
            }
            set {
                if ((this.PendingChangesField.Equals(value) != true)) {
                    this.PendingChangesField = value;
                    this.RaisePropertyChanged("PendingChanges");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string ImageID {
            get {
                return this.ImageIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageIDField, value) != true)) {
                    this.ImageIDField = value;
                    this.RaisePropertyChanged("ImageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string[] Subscribers {
            get {
                return this.SubscribersField;
            }
            set {
                if ((object.ReferenceEquals(this.SubscribersField, value) != true)) {
                    this.SubscribersField = value;
                    this.RaisePropertyChanged("Subscribers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public Torshify.Origo.Shell.QueryService.Track[] Tracks {
            get {
                return this.TracksField;
            }
            set {
                if ((object.ReferenceEquals(this.TracksField, value) != true)) {
                    this.TracksField = value;
                    this.RaisePropertyChanged("Tracks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.torshify/v1", ConfigurationName="QueryService.QueryService")]
    public interface QueryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.torshify/v1/QueryService/Query", ReplyAction="http://schemas.torshify/v1/QueryService/QueryResponse")]
        Torshify.Origo.Shell.QueryService.QueryResult Query([System.ServiceModel.MessageParameterAttribute(Name="query")] string query1, int trackOffset, int trackCount, int albumOffset, int albumCount, int artistOffset, int artistCount);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://schemas.torshify/v1/QueryService/Query", ReplyAction="http://schemas.torshify/v1/QueryService/QueryResponse")]
        System.IAsyncResult BeginQuery(string query, int trackOffset, int trackCount, int albumOffset, int albumCount, int artistOffset, int artistCount, System.AsyncCallback callback, object asyncState);
        
        Torshify.Origo.Shell.QueryService.QueryResult EndQuery(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.torshify/v1/QueryService/AlbumBrowse", ReplyAction="http://schemas.torshify/v1/QueryService/AlbumBrowseResponse")]
        Torshify.Origo.Shell.QueryService.AlbumBrowseResult AlbumBrowse(string albumId);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://schemas.torshify/v1/QueryService/AlbumBrowse", ReplyAction="http://schemas.torshify/v1/QueryService/AlbumBrowseResponse")]
        System.IAsyncResult BeginAlbumBrowse(string albumId, System.AsyncCallback callback, object asyncState);
        
        Torshify.Origo.Shell.QueryService.AlbumBrowseResult EndAlbumBrowse(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.torshify/v1/QueryService/ArtistBrowse", ReplyAction="http://schemas.torshify/v1/QueryService/ArtistBrowseResponse")]
        Torshify.Origo.Shell.QueryService.ArtistBrowseResult ArtistBrowse(string artistId, Torshify.Origo.Shell.QueryService.ArtistBrowsingType type);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://schemas.torshify/v1/QueryService/ArtistBrowse", ReplyAction="http://schemas.torshify/v1/QueryService/ArtistBrowseResponse")]
        System.IAsyncResult BeginArtistBrowse(string artistId, Torshify.Origo.Shell.QueryService.ArtistBrowsingType type, System.AsyncCallback callback, object asyncState);
        
        Torshify.Origo.Shell.QueryService.ArtistBrowseResult EndArtistBrowse(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.torshify/v1/QueryService/GetPlaylist", ReplyAction="http://schemas.torshify/v1/QueryService/GetPlaylistResponse")]
        Torshify.Origo.Shell.QueryService.Playlist GetPlaylist(string link);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://schemas.torshify/v1/QueryService/GetPlaylist", ReplyAction="http://schemas.torshify/v1/QueryService/GetPlaylistResponse")]
        System.IAsyncResult BeginGetPlaylist(string link, System.AsyncCallback callback, object asyncState);
        
        Torshify.Origo.Shell.QueryService.Playlist EndGetPlaylist(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QueryServiceChannel : Torshify.Origo.Shell.QueryService.QueryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public QueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Torshify.Origo.Shell.QueryService.QueryResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Torshify.Origo.Shell.QueryService.QueryResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlbumBrowseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AlbumBrowseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Torshify.Origo.Shell.QueryService.AlbumBrowseResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Torshify.Origo.Shell.QueryService.AlbumBrowseResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ArtistBrowseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ArtistBrowseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Torshify.Origo.Shell.QueryService.ArtistBrowseResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Torshify.Origo.Shell.QueryService.ArtistBrowseResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPlaylistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPlaylistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Torshify.Origo.Shell.QueryService.Playlist Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Torshify.Origo.Shell.QueryService.Playlist)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueryServiceClient : System.ServiceModel.ClientBase<Torshify.Origo.Shell.QueryService.QueryService>, Torshify.Origo.Shell.QueryService.QueryService {
        
        private BeginOperationDelegate onBeginQueryDelegate;
        
        private EndOperationDelegate onEndQueryDelegate;
        
        private System.Threading.SendOrPostCallback onQueryCompletedDelegate;
        
        private BeginOperationDelegate onBeginAlbumBrowseDelegate;
        
        private EndOperationDelegate onEndAlbumBrowseDelegate;
        
        private System.Threading.SendOrPostCallback onAlbumBrowseCompletedDelegate;
        
        private BeginOperationDelegate onBeginArtistBrowseDelegate;
        
        private EndOperationDelegate onEndArtistBrowseDelegate;
        
        private System.Threading.SendOrPostCallback onArtistBrowseCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetPlaylistDelegate;
        
        private EndOperationDelegate onEndGetPlaylistDelegate;
        
        private System.Threading.SendOrPostCallback onGetPlaylistCompletedDelegate;
        
        public QueryServiceClient() {
        }
        
        public QueryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QueryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<QueryCompletedEventArgs> QueryCompleted;
        
        public event System.EventHandler<AlbumBrowseCompletedEventArgs> AlbumBrowseCompleted;
        
        public event System.EventHandler<ArtistBrowseCompletedEventArgs> ArtistBrowseCompleted;
        
        public event System.EventHandler<GetPlaylistCompletedEventArgs> GetPlaylistCompleted;
        
        public Torshify.Origo.Shell.QueryService.QueryResult Query(string query1, int trackOffset, int trackCount, int albumOffset, int albumCount, int artistOffset, int artistCount) {
            return base.Channel.Query(query1, trackOffset, trackCount, albumOffset, albumCount, artistOffset, artistCount);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginQuery(string query, int trackOffset, int trackCount, int albumOffset, int albumCount, int artistOffset, int artistCount, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginQuery(query, trackOffset, trackCount, albumOffset, albumCount, artistOffset, artistCount, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Torshify.Origo.Shell.QueryService.QueryResult EndQuery(System.IAsyncResult result) {
            return base.Channel.EndQuery(result);
        }
        
        private System.IAsyncResult OnBeginQuery(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string query = ((string)(inValues[0]));
            int trackOffset = ((int)(inValues[1]));
            int trackCount = ((int)(inValues[2]));
            int albumOffset = ((int)(inValues[3]));
            int albumCount = ((int)(inValues[4]));
            int artistOffset = ((int)(inValues[5]));
            int artistCount = ((int)(inValues[6]));
            return this.BeginQuery(query, trackOffset, trackCount, albumOffset, albumCount, artistOffset, artistCount, callback, asyncState);
        }
        
        private object[] OnEndQuery(System.IAsyncResult result) {
            Torshify.Origo.Shell.QueryService.QueryResult retVal = this.EndQuery(result);
            return new object[] {
                    retVal};
        }
        
        private void OnQueryCompleted(object state) {
            if ((this.QueryCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.QueryCompleted(this, new QueryCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void QueryAsync(string query, int trackOffset, int trackCount, int albumOffset, int albumCount, int artistOffset, int artistCount) {
            this.QueryAsync(query, trackOffset, trackCount, albumOffset, albumCount, artistOffset, artistCount, null);
        }
        
        public void QueryAsync(string query, int trackOffset, int trackCount, int albumOffset, int albumCount, int artistOffset, int artistCount, object userState) {
            if ((this.onBeginQueryDelegate == null)) {
                this.onBeginQueryDelegate = new BeginOperationDelegate(this.OnBeginQuery);
            }
            if ((this.onEndQueryDelegate == null)) {
                this.onEndQueryDelegate = new EndOperationDelegate(this.OnEndQuery);
            }
            if ((this.onQueryCompletedDelegate == null)) {
                this.onQueryCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnQueryCompleted);
            }
            base.InvokeAsync(this.onBeginQueryDelegate, new object[] {
                        query,
                        trackOffset,
                        trackCount,
                        albumOffset,
                        albumCount,
                        artistOffset,
                        artistCount}, this.onEndQueryDelegate, this.onQueryCompletedDelegate, userState);
        }
        
        public Torshify.Origo.Shell.QueryService.AlbumBrowseResult AlbumBrowse(string albumId) {
            return base.Channel.AlbumBrowse(albumId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAlbumBrowse(string albumId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAlbumBrowse(albumId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Torshify.Origo.Shell.QueryService.AlbumBrowseResult EndAlbumBrowse(System.IAsyncResult result) {
            return base.Channel.EndAlbumBrowse(result);
        }
        
        private System.IAsyncResult OnBeginAlbumBrowse(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string albumId = ((string)(inValues[0]));
            return this.BeginAlbumBrowse(albumId, callback, asyncState);
        }
        
        private object[] OnEndAlbumBrowse(System.IAsyncResult result) {
            Torshify.Origo.Shell.QueryService.AlbumBrowseResult retVal = this.EndAlbumBrowse(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAlbumBrowseCompleted(object state) {
            if ((this.AlbumBrowseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AlbumBrowseCompleted(this, new AlbumBrowseCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AlbumBrowseAsync(string albumId) {
            this.AlbumBrowseAsync(albumId, null);
        }
        
        public void AlbumBrowseAsync(string albumId, object userState) {
            if ((this.onBeginAlbumBrowseDelegate == null)) {
                this.onBeginAlbumBrowseDelegate = new BeginOperationDelegate(this.OnBeginAlbumBrowse);
            }
            if ((this.onEndAlbumBrowseDelegate == null)) {
                this.onEndAlbumBrowseDelegate = new EndOperationDelegate(this.OnEndAlbumBrowse);
            }
            if ((this.onAlbumBrowseCompletedDelegate == null)) {
                this.onAlbumBrowseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAlbumBrowseCompleted);
            }
            base.InvokeAsync(this.onBeginAlbumBrowseDelegate, new object[] {
                        albumId}, this.onEndAlbumBrowseDelegate, this.onAlbumBrowseCompletedDelegate, userState);
        }
        
        public Torshify.Origo.Shell.QueryService.ArtistBrowseResult ArtistBrowse(string artistId, Torshify.Origo.Shell.QueryService.ArtistBrowsingType type) {
            return base.Channel.ArtistBrowse(artistId, type);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginArtistBrowse(string artistId, Torshify.Origo.Shell.QueryService.ArtistBrowsingType type, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginArtistBrowse(artistId, type, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Torshify.Origo.Shell.QueryService.ArtistBrowseResult EndArtistBrowse(System.IAsyncResult result) {
            return base.Channel.EndArtistBrowse(result);
        }
        
        private System.IAsyncResult OnBeginArtistBrowse(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string artistId = ((string)(inValues[0]));
            Torshify.Origo.Shell.QueryService.ArtistBrowsingType type = ((Torshify.Origo.Shell.QueryService.ArtistBrowsingType)(inValues[1]));
            return this.BeginArtistBrowse(artistId, type, callback, asyncState);
        }
        
        private object[] OnEndArtistBrowse(System.IAsyncResult result) {
            Torshify.Origo.Shell.QueryService.ArtistBrowseResult retVal = this.EndArtistBrowse(result);
            return new object[] {
                    retVal};
        }
        
        private void OnArtistBrowseCompleted(object state) {
            if ((this.ArtistBrowseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ArtistBrowseCompleted(this, new ArtistBrowseCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ArtistBrowseAsync(string artistId, Torshify.Origo.Shell.QueryService.ArtistBrowsingType type) {
            this.ArtistBrowseAsync(artistId, type, null);
        }
        
        public void ArtistBrowseAsync(string artistId, Torshify.Origo.Shell.QueryService.ArtistBrowsingType type, object userState) {
            if ((this.onBeginArtistBrowseDelegate == null)) {
                this.onBeginArtistBrowseDelegate = new BeginOperationDelegate(this.OnBeginArtistBrowse);
            }
            if ((this.onEndArtistBrowseDelegate == null)) {
                this.onEndArtistBrowseDelegate = new EndOperationDelegate(this.OnEndArtistBrowse);
            }
            if ((this.onArtistBrowseCompletedDelegate == null)) {
                this.onArtistBrowseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnArtistBrowseCompleted);
            }
            base.InvokeAsync(this.onBeginArtistBrowseDelegate, new object[] {
                        artistId,
                        type}, this.onEndArtistBrowseDelegate, this.onArtistBrowseCompletedDelegate, userState);
        }
        
        public Torshify.Origo.Shell.QueryService.Playlist GetPlaylist(string link) {
            return base.Channel.GetPlaylist(link);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetPlaylist(string link, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPlaylist(link, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Torshify.Origo.Shell.QueryService.Playlist EndGetPlaylist(System.IAsyncResult result) {
            return base.Channel.EndGetPlaylist(result);
        }
        
        private System.IAsyncResult OnBeginGetPlaylist(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string link = ((string)(inValues[0]));
            return this.BeginGetPlaylist(link, callback, asyncState);
        }
        
        private object[] OnEndGetPlaylist(System.IAsyncResult result) {
            Torshify.Origo.Shell.QueryService.Playlist retVal = this.EndGetPlaylist(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPlaylistCompleted(object state) {
            if ((this.GetPlaylistCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPlaylistCompleted(this, new GetPlaylistCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPlaylistAsync(string link) {
            this.GetPlaylistAsync(link, null);
        }
        
        public void GetPlaylistAsync(string link, object userState) {
            if ((this.onBeginGetPlaylistDelegate == null)) {
                this.onBeginGetPlaylistDelegate = new BeginOperationDelegate(this.OnBeginGetPlaylist);
            }
            if ((this.onEndGetPlaylistDelegate == null)) {
                this.onEndGetPlaylistDelegate = new EndOperationDelegate(this.OnEndGetPlaylist);
            }
            if ((this.onGetPlaylistCompletedDelegate == null)) {
                this.onGetPlaylistCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPlaylistCompleted);
            }
            base.InvokeAsync(this.onBeginGetPlaylistDelegate, new object[] {
                        link}, this.onEndGetPlaylistDelegate, this.onGetPlaylistCompletedDelegate, userState);
        }
    }
}
