//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Torshify.Origo.Shell.TrackPlayerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.torshify/v1", ConfigurationName="TrackPlayerService.TrackPlayerService")]
    public interface TrackPlayerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.torshify/v1/TrackPlayerService/Play", ReplyAction="http://schemas.torshify/v1/TrackPlayerService/PlayResponse")]
        void Play(string trackId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TrackPlayerServiceChannel : Torshify.Origo.Shell.TrackPlayerService.TrackPlayerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrackPlayerServiceClient : System.ServiceModel.ClientBase<Torshify.Origo.Shell.TrackPlayerService.TrackPlayerService>, Torshify.Origo.Shell.TrackPlayerService.TrackPlayerService {
        
        public TrackPlayerServiceClient() {
        }
        
        public TrackPlayerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TrackPlayerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrackPlayerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrackPlayerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Play(string trackId) {
            base.Channel.Play(trackId);
        }
    }
}
